USE dataanalytics;

SELECT COUNT(*) AS TOTAL_NO_OF_CUSTOMERS
FROM Customers;

-- Find the total number of products.  
SELECT COUNT(*) AS TOTAL_NO_OF_PRODUCTS
FROM products;

-- Find the total number of orders.

SELECT COUNT(*) AS TOTAL_NO_OF_ORDERS
FROM orders;

-- Display the most expensive product.

SELECT ProductName, Price
FROM products
ORDER BY Price
LIMIT 1;

-- Display all products whose price is greater than ₹1000.
SELECT ProductName, Category, Price
FROM products
WHERE Price > 1000;

-- Find the number of customers in each city.

SELECT City, COUNT(CustomerID) AS NO_OF_CUSTOMERS
FROM customers
GROUP BY City;

-- Find the number of products in each category.
SELECT Category, COUNT(ProductID) AS NO_OF_PRODUCTS
FROM products
GROUP BY Category;

-- Find the average product price in each category.

SELECT Category, AVG(Price) AS AVG_PRODUCT_PRICE
FROM products
GROUP BY Category;

-- Find the most expensive product price in each category.

SELECT Category, MAX(Price) AS MOST_EXPENSIVE
FROM products
GROUP BY Category;

-- Find all categories where the average product price is greater than ₹1000.

SELECT Category, AVG(Price) AS AVG_PRICE_GREATER_THAN_1K
FROM products
GROUP BY Category
HAVING AVG(Price) > 1000;

-- 11. Generate a report containing each customer's name, city, and the order ID for every order they have placed.

SELECT Name, City, OrderID
FROM customers
INNER JOIN orders
ON customers.CustomerID = orders.CustomerID;

-- 12.Generate a report showing each customer's name, the product they purchased, and the quantity purchased.

SELECT Name, ProductName, Quantity
FROM customers
INNER JOIN orders
ON customers.CustomerID = orders.CustomerID
INNER JOIN products
ON products.ProductID = orders.ProductID;

-- Create a detailed sales report containing:

-- Customer Name Product Name Category Price Quantity Purchased
SELECT Name, ProductName, Category, Price, Quantity
FROM customers
INNER JOIN orders
ON customers.CustomerID = orders.CustomerID
INNER JOIN products
ON products.ProductID = orders.ProductID;

-- Find the total quantity purchased by each customer.

SELECT Name, SUM(Quantity) AS TOTAL_QUANTITY_PURCHASED
FROM customers
INNER JOIN orders
ON customers.CustomerID = orders.CustomerID
GROUP BY Name;

-- Find the top 5 customers who purchased the highest total quantity.

SELECT Name, SUM(Quantity)
FROM customers
INNER JOIN orders
ON customers.CustomerID = orders.CustomerID
GROUP BY Name
ORDER BY SUM(Quantity) DESC
LIMIT 5;

-- 16. Find the total revenue generated.

SELECT SUM(Price * Quantity) AS TOTAL_REVENUE
FROM products
INNER JOIN orders
ON products.ProductID = orders.ProductID;

-- Find the total revenue generated by each product.
SELECT ProductName, SUM(Price * Quantity) AS TOTAL_REVENUE
FROM products
INNER JOIN orders
ON products.ProductID = orders.ProductID
GROUP BY ProductName;

-- Find the total revenue generated by each category.

SELECT Category, SUM(Price * Quantity) AS TOTAL_REVENUE
FROM products
INNER JOIN orders
ON products.ProductID = orders.ProductID
GROUP BY Category;

-- Find the top 5 customers who spent the most money.

SELECT Name, SUM(Price * Quantity) AS TOTAL_SPENT
FROM customers
INNER JOIN orders
ON customers.CustomerID = orders.CustomerID
INNER JOIN products
ON products.ProductID = orders.ProductID
GROUP BY Name
ORDER BY SUM(Price * Quantity) DESC
LIMIT 5;

-- 20. Find the city that generated the highest total revenue.

SELECT City, SUM(Price * Quantity) AS TOTAL_REVENUE
FROM customers
INNER JOIN orders
ON customers.CustomerID = orders.CustomerID
INNER JOIN products
ON products.ProductID = orders.ProductID
GROUP BY City
ORDER BY SUM(Price * Quantity) DESC
LIMIT 1;

-- 21 Find the customers who have never placed any order.

SELECT Name
FROM customers
LEFT JOIN orders
ON customers.CustomerID = orders.CustomerID
WHERE OrderID IS NULL;

-- 22 Find the products that have never been ordered

SELECT ProductName
FROM products
LEFT JOIN orders
ON products.ProductID = orders.ProductID
WHERE OrderID IS NULL;

-- 23. Find the average order value.
SELECT AVG(Price * Quantity) AS AVERAGE
FROM products
INNER JOIN orders
ON products.ProductID = orders.ProductID;

-- 24 Find the top-selling product based on total quantity sold.

SELECT ProductName, SUM(Quantity) AS TOTAL_QUANTITY_SOLD
FROM products
INNER JOIN orders
ON products.ProductID = orders.ProductID
GROUP BY ProductName
ORDER BY SUM(Quantity) DESC
LIMIT 1;

-- 25 Generate a report containing:

SELECT ProductName, Category, SUM(Quantity) AS TOTAL_QUANTITY_SOLD, SUM((Price * Quantity)) AS TOTAL_REVENUE
FROM products
INNER JOIN orders
ON products.ProductID = orders.ProductID
GROUP BY ProductName, Category
ORDER BY SUM((Price * Quantity)) DESC;